### ISSUE TITLE
Error on deploy the hello flight mission 

### ISSUE THREAD

**Issue by AIRmarket** [Parrot-Developers/airsdk-samples#1]
Hi
we successfully deploy the flight mission example using the provided command on documentation 
`./build.sh -p hello-pc -t all -j`
and generated the output image, 
`out/hello-pc/images/com.parrot.missions.samples.hello.tar.gz`
But running the following command to deploy on simulation :
`./build.sh -p hello-pc -t sync --unsigned --reboot`
It is showing the following error:
```
 ./build.sh -p hello-pc -t sync --unsigned --reboot
[I] Starting task 'sync' with args: --unsigned --reboot
[I] In '/home/airmarket/airsdk': curl -i -X PUT 'http://anafi-ai.local/api/v1/mission/missions/?allow_overwrite=yes&allow_unsigned=yes' --data-binary @/home/airmarket/airsdk/out/hello-pc/images/com.parrot.missions.samples.hello.tar.gz
curl: (52) Empty reply from server
[E] Command failed (returncode=52)
```
We are sure that the simulation is running. 

Regards

**Comment by Ronan0912** [comment]
Hello AirMarket,

Please open a topic on the Parrot developer forum: https://forum.developer.parrot.com/c/anafi-partnerships/air-market/75

Also, to fix the issue ensure that you have an up to date build workspace:

$ repo sync
$ ./build.sh -p pc -t download-base-sdk
$ ./build.sh -p pc -t all -j

and ensure that you have the latest firmware pc version from the partners FTP: 7.0.0-rc24

Thanks,

CC @JeromeBouvard
